10 INPUT"ENTER A NUMBER";N
20 print "ABS(N)=";ABS(N)
25 print "ATN(N)=";ATN(N)
30 print "COS(N)=";COS(N)
40 print "EXP(N)=";EXP(N)
50 print "INT(N)=";INT(N)
60 print "LOG(N)=";LOG(N)
70 print "SGN(N)=";SGN(N)
80 print "SQR(N)=";SQR(N)
90 print "TAN(N)=";TAN(N)
